# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Siffer
email: blog@luben.se
description: >- # this means to ignore newlines until "baseurl:"
  Blogging is for nerds!
baseurl: "" # the subpath of your site, e.g. /blog
url: "blog.luben.se" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  drinfiniteexplorer

# Build settings
theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-paginate
  - gemoji

#bulma stuff
paginate: 5
paginate_path: "/blog/page:num"


markdown: kramdown

# https://github.com/jekyll/jekyll/issues/4619#issuecomment-191267346
kramdown:
  #parse_block_html: true
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: bash
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
